// Generated by CoffeeScript 1.3.3
var bouncy, db, follow, freeway, log, nconf, opts, pin, start, updateSettings,
  __hasProp = {}.hasOwnProperty,
  _this = this;

log = console.log;

pin = require('linchpin');

bouncy = require('bouncy');

follow = require('follow');

nconf = require('nconf');

nconf.env().file({
  file: "./config.json"
});

db = nconf.get('datastore');

freeway = require('nano')(db);

follow = require('follow');

opts = {};

nconf.set('default', "https://localhost:9000");

updateSettings = function() {
  var _this = this;
  return freeway.get('settings', function(e, settings) {
    var k, v;
    if (e) {
      return log(e);
    }
    for (k in settings) {
      if (!__hasProp.call(settings, k)) continue;
      v = settings[k];
      if (k[0] !== '_') {
        nconf.set(k, v);
      }
    }
    pin.emit('settings:loaded');
    return log('Updated Settings from CouchDb.....');
  });
};

start = function(port) {
  var server,
    _this = this;
  server = bouncy(opts, function(req, bounce) {
    var target, xtoken;
    xtoken = req.headers['x-token'];
    target = nconf.get('default');
    if ((xtoken != null) && nconf.get('tokens').indexOf(xtoken) >= 0) {
      target = req.headers.host;
    }
    log("Bounced to " + target + " on " + ((new Date()).toString()));
    try {
      return bounce(target);
    } catch (err) {
      log(err.message);
      return bounce('http://google.com');
    }
  });
  server.on("error", function(err) {
    return log(err.message);
  });
  return server.listen(port);
};

follow({
  db: db
}, function(e, change) {
  if (e) {
    return log(e);
  }
  if (change.id === 'settings') {
    return updateSettings();
  }
});

pin.on('getKEY', function() {
  return freeway.attachment.get('settings', nconf.get('key'), function(err, key) {
    if (err != null) {
      return log(err);
    }
    opts.key = key.toString();
    return pin.emit('getCERT');
  });
});

pin.on('getCERT', function() {
  return freeway.attachment.get('settings', nconf.get('cert'), function(err, cert) {
    if (err != null) {
      return log(err);
    }
    opts.cert = cert.toString();
    return pin.emit('LOADED', null);
  });
});

module.exports = function(port) {
  pin.once('LOADED', function(err) {
    log("Starting server on port " + port + "...");
    return start(port);
  });
  updateSettings();
  return pin.once('settings:loaded', function() {
    pin.emit('getKEY');
    log('Welcome to Freeway v 1.0.0alpha3');
    return log('Initializing...');
  });
};
